version: '3'
services:
  XXXX:
    ports:
      - XXXX:XXX/udp
      -
    volumes:
      - XXXX:/var/ts3server/
    environment:
      TS3SERVER_LICENSE: accept
    image: teampeak
    container_name: XXXX
    restart: always
