version: '3'
services:
  terraria-ratpack:
    ports:
      - 7777:7777
    volumes:
      - /home/docker/docker-volumes/terraria-ratpack:/world
    command: '-world /world/ratpack.wld'
    image: ryshe/terraria:latest
    container_name: terraria-ratpack
    restart: always

#sudo docker run -it -p 7777:7777 -v /home/docker/docker-volumes/terraria-ratpack:/world --name="ratpack-terraria" ryshe/terraria:latest
