version: '3'
services:
  ratpack-terraria:
    ports:
      - 7777:7777
    volumes:
      - /home/docker/docker-volumes/ratpack-terraria:/world
    command: '-world /world/ratpack.wld'
    image: ryshe/terraria:latest
    container_name: ratpack-terraria
    restart: always


