version: '3'
services:
  terraria-ratpack:
    ports:
      - 7777:7777
    volumes:
      - /home/docker/docker-volumes/terraria-ratpack:/world
    image: ryshe/terraria:latest
    container_name: terraria-ratpack
    restart: always

