version: '3'
services:
  terraria-ratpack:
    ports:
      - 7777:7777
    volumes:
      - /home/odd/docker-volumes/terraria:/world
    image: ryshe/terraria:latest
    container_name: terraria-ratpack
    restart: always