version: '3'
services:
  teamspeak:
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    volumes:
      - /home/odd/docker-volumes/teamspeak:/var/ts3server/
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: odd
      TS3SERVER_DB_PASSWORD: odda
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    image: teamspeak
    container_name: teamspeak-ratpack
    restart: always
  db:
    environment:
      MYSQL_ROOT_PASSWORD: odda
      MYSQL_DATABASE: teamspeak
    container_name: teamspeak-database
    image: mariadb
    restart: always