version: '3'
services:
  openttd-ratpack:
    ports:
      - 3979:3979/tcp
      - 3979:3979/udp
    volumes: 
      - /home/docker/docker-volumes/.openttd/openttd.cfg:/config/openttd.cfg:ro
    image: redditopenttd/openttd
    container_name: openttd-ratpack
    restart: always

