version: '3'
services:
  ratpack-openttd:
    ports:
      - 3979:3979/tcp
      - 3979:3979/udp
    volumes: 
      - home/docker/ratpack/containers/openttd/ratpack-openttd/openttd.cfg:/config/openttd.cfg:ro
    image: redditopenttd/openttd
    container_name: ratpack-openttd
    restart: always

