version: '3'
services:
  openttd-ratpack:
    ports:
      - 3979:3979/tcp
      - 3979:3979/udp
    volumes:
      - /home/docker/docker-volumes/openttd:/home/openttd/.openttd
    environment:
      loadgame: "true"
      savename: ratpack.sav
    image: bateau/openttd
    container_name: openttd-ratpack
    restart: always